# Generated by Django 5.0.3 on 2024-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=123456, max_length=8),
            preserve_default=False,
        ),
    ]
