# Generated by Django 5.0.3 on 2024-04-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
