# Generated by Django 5.0.3 on 2024-04-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название курса')),
                ('image', models.ImageField(upload_to='course/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название урока')),
                ('image', models.ImageField(upload_to='lesson/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.TextField(verbose_name='Видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
        ),
    ]
